network:
  #接続先のホスト名を指定
  dest_hostname: "debian.local"
  tcp_json_port: 55555
  udp_send_image_port: 50000

camera:
  #1台のみ使用
  cam_device: "/dev/video0"
  width: 1280
  height: 960
  # "MJPEG" or "YUV422" のみ指定可能
  default_fmt: "MJPEG"

image_processor:
  # 0 - 100
  jpeg_quality: 90

  onnx_model_path: "./models/best.onnx"
  band_model_path: "./models/band_classifier_rf.pkl"
  color_model_path: "./models/resistor_color_rf_merged.pkl"
  
python:
  # ex /home/$USER/python/venv/
  venv_path: "/home/sawada/python/venv/"
  # ex /home/$USER/cam_module/src/inference/
  script_path: "./src/inference"
